# Hugo template
# All available Hugo versions are listed here:
# https://gitlab.com/pages/hugo/container-registry

image: registry.gitlab.com/pages/hugo/hugo_extended:latest

variables:
    GIT_SUBMODULE_STRATEGY: recursive

test:
    script:
        - hugo
    except:
        - master

pages:
    script:
        - hugo --buildDrafts --buildFuture
    artifacts:
        paths:
            - public
    only:
        - master